use_frameworks!

target 'tinyNetLib_Example' do
  pod 'tinyNetLib', :path => '../'

  target 'tinyNetLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
